[main]
include = "~/.config/fuzzel/themes/noctalia"
font=adwaita sans:size=13
terminal=foot -e
lines=9
width=35
horizontal-pad=40
vertical-pad=15
inner-pad=5
line-height=25

[colors]
background=131316ff

[border]
width=2
radius=10

[dmenu]
# dmenu-* options

[key-bindings]
confirmed-snippet=Return KP_Enter
execute=Return KP_Enter Control+l
confirm-selected=Control+m Control+Shift+m
custom-1=Control+Return Control+h
custom-2=Mod1+e
custom-3=Mod1+s
custom-4=Mod1+c
custom-5=Mod1+f
custom-6=Mod1+b
custom-7=Mod1+p
custom-8=Mod1+d
custom-9=Mod1+m
delete-prev=BackSpace
delete-prev-word=Mod1+BackSpace Control+BackSpace
delete-line-forward=none
delete-next-word=Mod1+d
move-left=Control+b Shift+Left
move-right=Control+f Shift+Right
cursor-char-next=Control+k
cursor-char-prev=Control+j
cursor-word-next=Control+w
cursor-word-prev=Control+s
cursor-line-start=Control+a
cursor-line-end=Control+e
move-selected-2345-left=Mod1+Left
move-selected-2345-right=Mod1+Right