# Noctalia
# Background: #131316
# Foreground: #e5e1e6
# Cursor:     #e5e1e6
cursor                  #e5e1e6
cursor_text_color       #131316
selection_background    #bec2ff
selection_foreground    #131316
background              #131316
foreground              #e5e1e6
border_color            #131316
color0                  #131316
color8                  #444559
color1                  #f38ba8
color9                  #ff8f9a
color2                  #a6e3a1
color10                 #a6e3a1
color3                  #f9e2af
color11                 #f9e2af
color4                  #89b4fa
color12                 #89b4fa
color5                  #f5c2e7
color13                 #f5c2e7
color6                  #94e2d5
color14                 #94e2d5
color7                  #bac2de
color15                 #a6adc8