# Chinese (Simplified) environment: locale settings + rime (雾凇拼音) + fonts
#
# Rime data packaging: the upstream fcitx5-rime-data has an empty default.yaml,
# which breaks rime_ice (and other schemas that include punctuator definitions).
# We build a complete rime-data package here by copying rime-ice and generating
# a proper default.yaml from librime's minimal/default.yaml upstream source.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  # rime-ice schema + dicts (the actual input engine data).
  rime-ice-data = pkgs.rime-ice;

  # Build a complete rime-data package:
  #   1. copy everything from rime-ice
  #   2. add distribution.yaml (fcitx5-rime expects this for deployment detection)
  #   3. add a proper default.yaml (upstream is empty, but rime_ice.schema.yaml
  #      does __include: default:/punctuator/* so it must exist)
  rime-data-fcitx5 = pkgs.runCommand "rime-data-fcitx5" { } ''
    set -eu
    mkdir -p $out/share/rime-data

    # Copy all rime-ice files (schemas, dicts, lua, opencc, symbols, etc.)
    cp -r ${rime-ice-data}/share/rime-data/* $out/share/rime-data/

    # fcitx5-rime deployment detection marker
    cat > $out/share/rime-data/distribution.yaml << 'YAML'
distribution:
  name: rime-ice
  version: "2026.01"
YAML

    # Proper default.yaml: without this, rime_ice.schema.yaml fails to build
    # because it __include:s default:/punctuator/* and other sections.
    # Source: https://raw.githubusercontent.com/rime/librime/2b7ccf2d/data/minimal/default.yaml
    cat > $out/share/rime-data/default.yaml << 'YAML'
# Rime default settings — generated by locales/zh-cn.nix
# Source: librime data/minimal/default.yaml
config_version: "0.16"

schema_list:
  - schema: rime_ice

switcher:
  caption: 〔方案選單〕

menu:
  page_size: 9

punctuator:
  full_shape:
    " " : { commit: "　" }
    "," : { commit: "，" }
    "." : { commit: "。" }
    "<" : [ "《", "〈", "«", "‹" ]
    ">" : [ "》", "〉", "»", "›" ]
    "/" : [ "／", "÷" ]
    "?" : { commit: "？" }
    ";" : { commit: "；" }
    ":" : { commit: "：" }
    "'" : { pair: [ "‘", "’" ] }
    '"' : { pair: [ "“", "”" ] }
    "\\" : [ "、", "＼" ]
    "|" : [ "・", "｜", "§", "¦" ]
    "`" : "｀"
    "~" : [ "〜", "～", "〰" ]
    "!" : { commit: "！" }
    "@" : [ "＠", "☯" ]
    "#" : [ "＃", "⌘" ]
    "%" : [ "％", "°", "℃" ]
    "$" : [ "￥", "$", "€", "£", "¥", "¢", "¤" ]
    "^" : { commit: "……" }
    "&" : "＆"
    "*" : [ "＊", "・", "·", "×", "※", "❂" ]
    "(" : "（"
    ")" : "）"
    "-" : "－"
    "_" : "——"
    "+" : "＋"
    "=" : "＝"
    "[" : [ "「", "【", "〔", "［" ]
    "]" : [ "」", "】", "〕", "］" ]
    "{" : [ "『", "〖", "｛" ]
    "}" : [ "』", "〗", "｝" ]
  half_shape:
    "," : { commit: "，" }
    "." : { commit: "。" }
    "<" : [ "《", "〈", "«", "‹" ]
    ">" : [ "》", "〉", "»", "›" ]
    "/" : [ "、", "/", "／", "÷" ]
    "?" : { commit: "？" }
    ";" : { commit: "；" }
    ":" : { commit: "：" }
    "'" : { pair: [ "‘", "’" ] }
    '"' : { pair: [ "“", "”" ] }
    "\\" : [ "、", "\\", "＼" ]
    "|" : [ "・", "|", "｜", "§", "¦" ]
    "`" : "`"
    "~" : [ "~", "〜", "～", "〰" ]
    "!" : { commit: "！" }
    "@" : "@"
    "#" : "#"
    "%" : [ "%", "％", "°", "℃" ]
    "$" : [ "￥", "$", "€", "£", "¥", "¢", "¤" ]
    "^" : { commit: "……" }
    "&" : "&"
    "*" : [ "*", "＊", "・", "·", "×", "※", "❂" ]
    "(" : "（"
    ")" : "）"
    "-" : "-"
    "_" : "——"
    "+" : "+"
    "=" : "="
    "[" : [ "「", "【", "〔", "［" ]
    "]" : [ "」", "】", "〕", "］" ]
    "{" : [ "『", "〖", "｛" ]
    "}" : [ "』", "〗", "｝" ]

key_binder:
  bindings:
    - { when: composing, accept: Control+p, send: Up }
    - { when: composing, accept: Control+n, send: Down }
    - { when: composing, accept: Control+b, send: Left }
    - { when: composing, accept: Control+f, send: Right }
    - { when: composing, accept: Control+a, send: Home }
    - { when: composing, accept: Control+e, send: End }
    - { when: composing, accept: Control+d, send: Delete }
    - { when: composing, accept: Control+g, send: Escape }
    - { when: composing, accept: Alt+v, send: Page_Up }
    - { when: composing, accept: Control+v, send: Page_Down }
    - { when: paging, accept: minus, send: Page_Up }
    - { when: has_menu, accept: equal, send: Page_Down }
    - { when: paging, accept: comma, send: Page_Up }
    - { when: has_menu, accept: period, send: Page_Down }
    - { when: always, accept: Control+Shift+2, toggle: ascii_mode }
    - { when: always, accept: Control+Shift+3, toggle: full_shape }
    - { when: always, accept: Shift+space, toggle: full_shape }
    - { when: always, accept: Control+period, toggle: ascii_punct }

recognizer:
  patterns:
    email: "^[a-z][-_.0-9a-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp:|mailto:).*$|^[a-z]+[.].+$"

ascii_composer:
  switch_key:
    Shift_L: inline_ascii
    Shift_R: commit_text
    Control_L: noop
    Control_R: noop
YAML
  '';
in
{
  options.locales.zh-cn.enable = lib.mkEnableOption "Chinese (Simplified) locale environment";

  config = lib.mkIf config.locales.zh-cn.enable {
    locales.supportedLocales = [ "zh_CN.UTF-8/UTF-8" ];

    i18n.extraLocaleSettings = {
      LC_ADDRESS = "zh_CN.UTF-8";
      LC_IDENTIFICATION = "zh_CN.UTF-8";
      LC_MEASUREMENT = "zh_CN.UTF-8";
      LC_MONETARY = "zh_CN.UTF-8";
      LC_NAME = "zh_CN.UTF-8";
      LC_NUMERIC = "zh_CN.UTF-8";
      LC_PAPER = "zh_CN.UTF-8";
      LC_TELEPHONE = "zh_CN.UTF-8";
      LC_TIME = "zh_CN.UTF-8";
    };

    # Fcitx5 with rime-ice.  Use our complete rime-data package instead of
    # the upstream one (which ships an empty default.yaml that breaks schema
    # compilation).  To add more languages, import their rime schemas here and
    # append them to the rimeDataPkgs list.
    i18n.inputMethod.fcitx5.addons = with pkgs; [
      (fcitx5-rime.override {
        rimeDataPkgs = [ rime-data-fcitx5 ];
      })
    ];

    fonts.fontconfig.defaultFonts = {
      sansSerif = [
        "Noto Sans CJK SC"
        "Noto Sans"
        "Noto Color Emoji"
      ];
      serif = [
        "Noto Serif CJK SC"
        "Noto Serif"
        "Noto Color Emoji"
      ];
    };
  };
}
