[config]

[templates]

# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

[templates.fcitx5]
input_path = '~/.config/noctalia/templates/fcitx5-theme.conf'
output_path = '~/.local/share/fcitx5/themes/Matugen/theme.conf'
post_hook= 'fcitx5 -r & disown '

[templates.gtk-folder]
input_path = '~/.config/noctalia/templates/gtk-folder/recolor.sh'
output_path = '~/.cache/matugen/recoloricons.sh'
post_hook = 'bash ~/.cache/matugen/recoloricons.sh &'

