# niri KDL config validation (no VM, no network: just `niri validate`).
#
# Why: home/niri/*.kdl is a set of `include`s parsed only at niri startup, so a
# typo (e.g. `spawn-sh` outside `binds {}`) survives `home-manager switch` and
# only shows up as a black screen / ignored keybinding after the next login.
# `niri validate` catches it in CI instead.
#
# The clavis/* fragments are generated by Clavis at runtime, so they are optional
# includes here; the check asserts they stay optional (a *required* include
# would break every niri start before Clavis ever runs) and that the fragment
# set matches upstream's FRAGMENTS tuple
# (scripts/system/niri_config.py):
#   effects, cursor, layer-rules, binds, outputs, minimize-animation
{ pkgs, ... }:
pkgs.runCommand "niri-config-validate"
  {
    nativeBuildInputs = [ pkgs.niri ];
  }
  ''
    set -euo pipefail

    src=${../home/niri}
    work=$TMPDIR/niri
    mkdir -p "$work/clavis"
    cp "$src"/*.kdl "$work/"

    # niri-hardware.kdl is generated per host (hosts/<host>/niri-hardware.kdl) and
    # is a hard `include`, so stub it for the standalone validation.
    printf '// stub for standalone validation\n' > "$work/niri-hardware.kdl"

    # Clavis writes these at runtime. Stub them with content that mirrors what
    # upstream NiriConfig.py actually generates (see scripts/system/niri_config.py
    # in the clavis-shell derivation) so the optional includes are really resolved
    # and parsed -- an include line pointing at a file Clavis never writes is
    # exactly the kind of breakage this check exists to catch.
    #
    # niri 26 KDL quirks to keep in mind while editing these stubs:
    #   * every child node goes on its own line -- a `}` on the same line as the
    #     last value is a parse error;
    #   * easing animations use `duration-ms N` (not `duration 150ms`);
    #   * `curve` accepts only ease-out-quad / ease-out-cubic / ease-out-expo
    #     / linear;
    #   * the xray=false branch below is the non-default one -- with xray left on
    #     (niri's default) the effects fragment is just a comment line.
    cat > "$work/clavis/effects.kdl" <<'EOF'
    layer-rule {
        match namespace="^clavis-shell-"
        background-effect {
            xray false
        }
    }
    window-rule {
        match title="^(clavis-control-center(-[a-z-]+)?|clavis-file-picker)$"
        background-effect {
            xray false
        }
    }
    EOF
    cat > "$work/clavis/cursor.kdl" <<'EOF'
    cursor {
        xcursor-theme "breeze_cursors"
        xcursor-size 24
        hide-when-typing
    }
    EOF
    cat > "$work/clavis/layer-rules.kdl" <<'EOF'
    layer-rule {
        match namespace="^clavis-overview-wallpaper$"
        place-within-backdrop true
    }
    layout {
        background-color "transparent"
    }
    EOF
    cat > "$work/clavis/outputs.kdl" <<'EOF'
    // Host-specific; left empty upstream too when niri has no saved output state.
    EOF
    # NOTE: upstream writes `animations { window-minimize-effect "scale" }` for
    # this fragment, but that node only exists in newer niri than this repo's
    # 26.04. Stub with a 26.04-parseable animation instead; the shapes match.
    cat > "$work/clavis/minimize-animation.kdl" <<'EOF'
    animations {
        window-open {
            duration-ms 150
            curve "ease-out-expo"
        }
    }
    EOF
    cat > "$work/clavis/binds.kdl" <<'EOF'
    binds {
        Mod+Space repeat=false {
            spawn "qs" "-c" "clavis" "ipc" "call" "spotlight" "toggle"
        }
    }
    EOF

    niri validate -c "$work/config.kdl"

    # Guard the invariant that keeps ~/.config/niri/config.kdl a read-only store
    # symlink: Clavis greps for these exact include lines and appends to
    # config.kdl when they are missing.
    for f in effects cursor layer-rules outputs minimize-animation binds; do
      grep -qF "include optional=true \"clavis/$f.kdl\"" "$work/config.kdl" \
        || { echo "config.kdl must contain: include optional=true \"clavis/$f.kdl\"" >&2; exit 1; }
    done

    # clavis/colors.kdl was retired upstream (the matugen niri palette fragment is
    # gone), so a leftover include would be a silently ignored no-op. Fail loudly
    # if someone re-adds it.
    if grep -qF 'clavis/colors.kdl' "$work/config.kdl"; then
      echo "config.kdl still includes clavis/colors.kdl, which upstream no longer generates" >&2
      exit 1
    fi

    # Every IPC call in binds.kdl must name a target/method that the shell
    # actually registers. The authoritative list lives in the shell source
    # (AppShell.qml, Modules/Keystone/Keystone.qml, Modules/Sidebars/*); the
    # methods used here are documented in the shell's docs/ipc.md.
    for call in \
      "spotlight toggle" \
      "spotlight openMode clipboard" \
      "spotlight web" \
      "control-center toggle general" \
      "control-center open general" \
      "keystone hub" \
      "keystone dashboard" \
      "keystone tools" \
      "sidebar toggle dashboard" \
      "sidebar toggle quicksettings" \
      "shortcut-map toggle" \
      "lock open" \
      "wallpaper random" ; do
      grep -qF "key ipc call $call" "$work/binds.kdl" \
        || { echo "binds.kdl lost the IPC call: key ipc call $call" >&2; exit 1; }
    done

    touch $out
  ''
