# niri KDL config validation (no VM, no network: just `niri validate`).
#
# Why: home/niri/*.kdl is a set of `include`s parsed only at niri startup, so a
# typo (e.g. `spawn-sh` outside `binds {}`) survives `home-manager switch` and
# only shows up as a black screen / ignored keybinding after the next login.
# `niri validate` catches it in CI instead.
#
# The three clavis/* fragments are generated by Clavis at runtime, so they are
# optional includes here; the check asserts they stay optional (a *required*
# include would break every niri start before Clavis ever runs).
{ pkgs, ... }:
pkgs.runCommand "niri-config-validate"
{
  nativeBuildInputs = [ pkgs.niri ];
} ''
  set -euo pipefail

  src=${../home/niri}
  work=$TMPDIR/niri
  mkdir -p "$work/clavis"
  cp "$src"/*.kdl "$work/"

  # niri-hardware.kdl is generated per host (hosts/<host>/niri-hardware.kdl) and
  # is a hard `include`, so stub it for the standalone validation.
  printf '// stub for standalone validation\n' > "$work/niri-hardware.kdl"

  # Clavis writes these at runtime; make sure the includes are optional and the
  # placeholder content itself parses (colors.kdl mirrors the matugen template,
  # cursor.kdl mirrors write_niri_cursor_config.sh).
  cat > "$work/clavis/colors.kdl" <<'EOF'
  layout {
      focus-ring {
          active-gradient from="#aabbccdd" to="#11223344" angle=135
          urgent-color "#ff0000"
      }
  }
  recent-windows {
      highlight {
          active-color "#aabbcc"
          urgent-color "#ff0000"
      }
  }
  EOF
  cat > "$work/clavis/effects.kdl" <<'EOF'
  layer-rule {
      match namespace="^clavis-shell-"
      background-effect {
          xray false
      }
  }
  EOF
  cat > "$work/clavis/cursor.kdl" <<'EOF'
  cursor {
      xcursor-theme "breeze_cursors"
      xcursor-size 24
      hide-when-typing
      hide-after-inactive-ms 3000
  }
  EOF

  niri validate -c "$work/config.kdl"

  # Guard the invariant that keeps ~/.config/niri/config.kdl a read-only store
  # symlink: Clavis greps for these exact include lines and appends to
  # config.kdl when they are missing.
  for f in clavis/colors.kdl clavis/effects.kdl clavis/cursor.kdl; do
    grep -qF "include optional=true \"$f\"" "$work/config.kdl" \
      || { echo "config.kdl must contain: include optional=true \"$f\"" >&2; exit 1; }
  done

  touch $out
''
